# Generated by Django 4.0.5 on 2022-06-20 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('fashion', 'Fashion'), ('electronic', 'Electronic'), ('home and kitchen', 'Home and kitchen'), ('travel', 'Travel'), ('toy', 'Toy'), ('beauty', 'Beauty'), ('food', 'Food'), ('stationery', 'stationery')], max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('pic', models.FileField(upload_to='product/')),
                ('description', models.TextField(max_length=200)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
