# Generated by Django 4.0.5 on 2022-06-21 05:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_product_category_mycart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('packing', 'Packing'), ('ready to dispatch', 'Ready to dispatch'), ('on the way', 'On the way'), ('ordered complate', 'Ordered complate')], default='pending', max_length=100)),
                ('payment_method', models.CharField(choices=[('cash on delivery', 'cash on delivery'), ('online', 'Online')], max_length=50)),
                ('total_amount', models.PositiveIntegerField()),
                ('ordered_date', models.DateField(default=datetime.date.today)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
