# Generated by Django 4.0.5 on 2022-06-21 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_buyproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyproduct',
            old_name='addres',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='buyproduct',
            old_name='user',
            new_name='buyer',
        ),
    ]
